/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as KonfiguratoriusRouteImport } from './routes/konfiguratorius'
import { Route as KrepselisRouteImport } from './routes/krepselis'
import { Route as SalygosRouteImport } from './routes/salygos'
import { Route as AuthenticatedValdymasRouteImport } from './routes/_authenticated/valdymas'
import { Route as KompiuteriaiIndexRouteImport } from './routes/kompiuteriai.index'
import { Route as KompiuteriaiSlugRouteImport } from './routes/kompiuteriai.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const KonfiguratoriusRoute = KonfiguratoriusRouteImport.update({
  id: '/konfiguratorius',
  path: '/konfiguratorius',
  getParentRoute: () => rootRouteImport,
} as any)
const KrepselisRoute = KrepselisRouteImport.update({
  id: '/krepselis',
  path: '/krepselis',
  getParentRoute: () => rootRouteImport,
} as any)
const SalygosRoute = SalygosRouteImport.update({
  id: '/salygos',
  path: '/salygos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedValdymasRoute = AuthenticatedValdymasRouteImport.update({
  id: '/valdymas',
  path: '/valdymas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const KompiuteriaiIndexRoute = KompiuteriaiIndexRouteImport.update({
  id: '/kompiuteriai/',
  path: '/kompiuteriai/',
  getParentRoute: () => rootRouteImport,
} as any)
const KompiuteriaiSlugRoute = KompiuteriaiSlugRouteImport.update({
  id: '/kompiuteriai/$slug',
  path: '/kompiuteriai/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/konfiguratorius': typeof KonfiguratoriusRoute
  '/krepselis': typeof KrepselisRoute
  '/salygos': typeof SalygosRoute
  '/valdymas': typeof AuthenticatedValdymasRoute
  '/kompiuteriai/$slug': typeof KompiuteriaiSlugRoute
  '/kompiuteriai/': typeof KompiuteriaiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/konfiguratorius': typeof KonfiguratoriusRoute
  '/krepselis': typeof KrepselisRoute
  '/salygos': typeof SalygosRoute
  '/valdymas': typeof AuthenticatedValdymasRoute
  '/kompiuteriai/$slug': typeof KompiuteriaiSlugRoute
  '/kompiuteriai': typeof KompiuteriaiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/konfiguratorius': typeof KonfiguratoriusRoute
  '/krepselis': typeof KrepselisRoute
  '/salygos': typeof SalygosRoute
  '/_authenticated/valdymas': typeof AuthenticatedValdymasRoute
  '/kompiuteriai/$slug': typeof KompiuteriaiSlugRoute
  '/kompiuteriai/': typeof KompiuteriaiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/konfiguratorius'
    | '/krepselis'
    | '/salygos'
    | '/valdymas'
    | '/kompiuteriai/$slug'
    | '/kompiuteriai/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/konfiguratorius'
    | '/krepselis'
    | '/salygos'
    | '/valdymas'
    | '/kompiuteriai/$slug'
    | '/kompiuteriai'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/konfiguratorius'
    | '/krepselis'
    | '/salygos'
    | '/_authenticated/valdymas'
    | '/kompiuteriai/$slug'
    | '/kompiuteriai/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  KonfiguratoriusRoute: typeof KonfiguratoriusRoute
  KrepselisRoute: typeof KrepselisRoute
  SalygosRoute: typeof SalygosRoute
  KompiuteriaiSlugRoute: typeof KompiuteriaiSlugRoute
  KompiuteriaiIndexRoute: typeof KompiuteriaiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konfiguratorius': {
      id: '/konfiguratorius'
      path: '/konfiguratorius'
      fullPath: '/konfiguratorius'
      preLoaderRoute: typeof KonfiguratoriusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/krepselis': {
      id: '/krepselis'
      path: '/krepselis'
      fullPath: '/krepselis'
      preLoaderRoute: typeof KrepselisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salygos': {
      id: '/salygos'
      path: '/salygos'
      fullPath: '/salygos'
      preLoaderRoute: typeof SalygosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/valdymas': {
      id: '/_authenticated/valdymas'
      path: '/valdymas'
      fullPath: '/valdymas'
      preLoaderRoute: typeof AuthenticatedValdymasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/kompiuteriai/': {
      id: '/kompiuteriai/'
      path: '/kompiuteriai'
      fullPath: '/kompiuteriai/'
      preLoaderRoute: typeof KompiuteriaiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kompiuteriai/$slug': {
      id: '/kompiuteriai/$slug'
      path: '/kompiuteriai/$slug'
      fullPath: '/kompiuteriai/$slug'
      preLoaderRoute: typeof KompiuteriaiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedValdymasRoute: typeof AuthenticatedValdymasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedValdymasRoute: AuthenticatedValdymasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  KonfiguratoriusRoute: KonfiguratoriusRoute,
  KrepselisRoute: KrepselisRoute,
  SalygosRoute: SalygosRoute,
  KompiuteriaiSlugRoute: KompiuteriaiSlugRoute,
  KompiuteriaiIndexRoute: KompiuteriaiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
